i18n-module.php

This resolves the issue that a warning message is shown if the API call doesn't have the `wp_locale` property for a particular translation set.

Added separate check to ensure the wp_locale property exists

---

i18n-module.php

Fixes #15 
This uses the same code used on https://github.com/Yoast/wordpress-seo/pull/6215
Since this module must be independent from other plugins, I guess we have to repeat some code.
Getting the native name of the locale would be a nice addition but as far as I see the `native_name` is not exposed in the GlotPress API and getting it by other means seems way too complicated.

Use the user locale for the locale.

---

src/i18n-module-wordpressorg.php
src/i18n-module.php

#Changed translate promo box to a notification. 
The notification doesn't look all that spectacular right now. I removed the image for now as I couldn't duplicate the previous style exactly as the glotpress-logo can't go further right in the notification window. (check out the third screenshot to see what I mean).
***Previous promobox:***
***As a notification:***
***As a notification with the image:***
For now I kept the text-only version. We probably want to add the image somehow, and I've asked for a styling suggestion that can be implemented in a different issue.
Test instructions. Using this branch. 
- Make sure https://github.com/Yoast/wordpress-seo/pull/7608 is checked out as well. 
- delete from wp_options the entry with option name _transient_yoast_i18n_wordpress-seo_promo_hide, …

6877 change translate box to notification

---

src/i18n-module.php

Reasoning:
* Initially the property is `null` (not set).
* The property may get initialized by it being passed in via `$args`. In that case, it is expected to be a `string`, but there is no type check anywhere, so it could be something else.
Having said that, changing this to a strict comparison could still create a passing condition, unless we also add an `is_string()` as well.

CS/QA: replace a loose comparison

---

README.md
src/i18n-module-wordpressorg.php
src/i18n-module.php

This is a safe change. Class names in PHP are case-insensitive, so changing the capitalization of the class names will not break any integrations, while it ensures compliance with the `Camel_Caps` class name rule.

CS: fix capitalization in class names

---

src/i18n-v3.php

* Add output escaping where appropriate.
* Whitelist one output call where the params are correctly escaped elsewhere. This whitelist won't have any effect until PHPCS has been activated (upcoming).

CS/XSS: escape all output

---

composer.json

This dependency will prevent packages with known security issues from being installed through Composer.
The package will always have to be at `dev-master` to make sure that the latest security information available will be used.
Refs:
* https://github.com/Roave/SecurityAdvisories
* https://www.bleepingcomputer.com/news/security/php-community-takes-steps-to-stop-installation-of-libraries-with-unpatched-bugs/
* https://websec.io/2018/03/10/Package-Protection-Roave-SecurityAdvisories.html

Security: add Roave/SecurityAdvisories dependency

---

.phpcs.xml.dist
.travis.yml
README.md
composer.json

This PR:
* Adds Yoast to the composer `--dev` dependencies
* Add the Dealerdirect PHPCS Composer plugin to the composer `--dev` dependencies to sort out the registration of the rulesets with PHPCS
* Adds a simple PHPCS ruleset based on the YoastCS ruleset
* Adds checking against this ruleset to the Travis script for PHP 7.2.
No need to add it to more builds as all sniffs are unit tested against all supported PHP versions to give the same results.
* Adds a Travis "build status" badge to the readme.

CS: add PHPCS ruleset and check via Travis

---

.phpcs.xml.dist

Use the new property array format. The old format is still supported for now, but will be removed in PHPCS 4.0.
See: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.3.0
As this repo does not have a `composer.lock` file, no other changes are needed AFAICS.

CS: Update PHPCS ruleset for PHPCS 3.3.0

---

.phpcs.xml.dist
composer.json
src/i18n-v3.php

* The `VIP` sniffs have been deprecated in WPCS 1.0.0 and are no longer included in the YoastCS ruleset.
* The `EscapeOutput` sniff has been moved to the `Security` category in WPCS 1.0.0.

PHPCS: Update to use YoastCS 1.0 / WPCS 1.0

---

.phpcs.xml.dist
composer.json

* Includes adding the PHPCS XSD to the custom ruleset which should now be valid as the minimum PHPCS requirement has gone up to PHPCS 3.3.2.
* Includes removing the DealerDirect Composer PHPCS plugin which now comes automatically with YoastCS.
No code CS changes needed.

Composer: require YoastCS 1.1.0

---

composer.json

Updates the CS requirements to YoastCS 1.2.2.
No changes to the code are needed.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/1.2.0
* https://github.com/Yoast/yoastcs/releases/tag/1.2.1
* https://github.com/Yoast/yoastcs/releases/tag/1.2.2

Composer: require YoastCS ^1.2.2

---

src/i18n-v3.php

- Fixes a bug where a 'You're using WordPress in a language we don't support yet.' notice would be shown for formal and informal locales when the locale actually was supported.
The wp_locale in the translation_sets object do not contain the _formal or _informal part. For example: the wp_locale of Dutch (Formal) is nl_NL. The information that it's formal is only in the `slug` property. Because this->locale does have the _formal or _informal part, the comparison with the wp_locale had an incorrect result for informal and formal languages. This commit adds an extra check in which the slug is appended to the locale if the slug is not 'default' (i.e. is 'informal' or 'formal'). This string is compared to this->locale to make sure the correct $set is returned.
On **wordpress-seo** trunk:
- Go …

Add extra check to handle formal and informal locales.

---

.phpcs.xml.dist
CHANGELOG.md
README.md
src/i18n-v3.php
src/i18n-wordpressorg-v3.php

This reverts commit 87aef6aa623a5076293064ebcd85de720d6e5fe5. 
Because capitalization matters when loading dependencies with composer like we do in our plugins, this is in a way a breaking change. That's why I'm reverting it for now.

Revert "CS: fix capitalization in class names"

---

.phpcs.xml.dist
composer.json

Ruleset updates:
* Remove dependencies related `exclude-pattern`. These are now contained within the YoastCS ruleset as of v1.3.0.
* Remove the `minimum_supported_wp_version` `config` directive. As of YoastCS 1.3.0, a default is set in the `Yoast` ruleset and should be followed by this repo.
The default in the `Yoast` ruleset at this time is `4.9`.
* Minor spelling fix in inline documentation.
* Add documentation as to why the `PEAR.NamingConventions.ValidClassName` sniff is (temporarily) excluded.

Composer: require YoastCS ^1.3.0 & update ruleset

---

.travis.yml
composer.json

Includes:
* Removing builds against PHP < 5.6.
* Removing the build against PHP 7.4 from allowed failures.
* Adding back a build against PHP `nightly` (PHP 8).
As the I18n module does not contain unit tests, these changes can already be made and made in one go.
Also:
* Travis hasn't supported `sudo` for quite a while now, so removing it.

Stop explicit support for PHP < 5.6 /  WP < 5.2

---

.phpcs.xml.dist
composer.json
src/i18n-v3.php

This updates the dependency in `composer.json`, as well as the PHPCS ruleset for YoastCS 2.0.0.
Ref: https://github.com/Yoast/yoastcs/releases/tag/2.0.0

PHPCS: Update to YoastCS 2.0.0

---

src/i18n-v3.php
src/i18n-wordpressorg-v3.php

> Tag |	Usage |	Description
> --- | --- | ---
> @access | private | Only used in limited circumstances, and only when private, such as for core-only functions or core classes implementing “private” APIs. Used directly below the `@since` line in block.
Source: https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#phpdoc-tags
If used at all, the `@access` tag should only be used on global functions/variables where the visibility can't be set via a modifier.
After this commit, there are two `@access private` tags remaining. These are set for `public` methods.
For those, it should be decided whether the method visibility is correct and if not, the method visibility should be changed.
Either way, the tag should be removed after this has been examined.

Docs: various minor tweaks

---

.travis.yml

.. to make sure that the command doesn't need to be updated in two places if anything changes.

Travis: use the Composer PHPCS script

---

composer.json
src/i18n-v3.php

* Update minimum allowed version of YoastCS from `2.0.0` to `2.1.0`.
As this module does not have a committed `composer.lock` file, all other related updates will be pulled in automatically, including version `0.7.0` from the DealerDirect Composer plugin (which is  compatible with Composer 2.0).
Relevant changes in YoastCS:
* The minimum supported WP version has changed to `5.4`.
* A new check for test doubles being named as such.
* A few bugfixes.
* Various sniffs now provide metrics.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/2.1.0

Composer: update YoastCS to v 2.1.0

---

README.md

In https://github.com/Yoast/wordpress-seo-premium/pull/3315 we have updated the box in Premium to reflect the upcoming switch from `translate.yoast.com` to TranslationsPress, but the latter uses a different URL format for the API which can't be built from the `glotpress_url` parameter.
We should change the docs to let devs know that the `api_url` param can be used in those kind of situations.

P3-576 Update docs to make explicit that the api_url parameter can be used as well

---

.travis.yml

At this time, the current PHP 8.0 version is `8.0.11`. The Travis PHP `8.0` image yields PHP `8.0.9`, which is good enough for PHP 8.0.
`nightly` however is PHP `8.0.3` and hasn't been updated since Feb 2021, so running tests against that image is completely useless at this time.
Notes:
* Tested `nightly` against all relevant `dist`s - `xenial`, `bionic` and `focal` and none have a more current image.
* The [PHP Build project](https://github.com/php-build/php-build/tree/master/share/php-build/definitions), which Travis pulls its images from, _does_ have a PHP `8.1snapshot` image available.
I've tested to see if that image is available on Travis, but unfortunately, no luck there either.

Travis: add build against PHP 8.0/remove nightly

---

.github/workflows/lint.yml

... so builds against PHP 8.1 should no longer be allowed to fail.

GH Actions: PHP 8.1 has been released

---

.github/workflows/cs.yml
.github/workflows/lint.yml

The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Refs:
* https://github.com/ramsey/composer-install/releases/tag/2.0.0
* https://github.com/ramsey/composer-install/releases/tag/2.0.1
* https://github.com/ramsey/composer-install/releases/tag/2.0.2

GH Actions: version update for `ramsey/composer-install`

---

.github/workflows/cs.yml
.github/workflows/lint.yml

A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 12 to Node 16).
Refs:
* https://github.com/actions/checkout/releases

GH Actions: version update for various predefined actions

---

.github/workflows/cs.yml
.github/workflows/lint.yml

If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
... after branch rename.

GH Actions: various tweaks

---

.github/workflows/cs.yml
.github/workflows/lint.yml

Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action we are using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like `8.1.11`.
> * The options passed via `composer-options`.
> * The dependency version setting as per `dependency-versions`.
> * The working directory as per `working-directory`.
> * A hash of the `composer.json` and/or `composer.lock` files.
This means that aside from other factors, the cache will always be busted when changes are made to the (committed) `composer.json` or the …

GH Actions: bust the cache semi-regularly
